"""S9 - the generation queue: every lexicon word, in the order to write data for.

The lexicon holds two kinds of word and they are not worth the same.

  tested    the word was one of the four options on a real question. This is
            the product. `stats.priority` already ranks it: being the correct
            answer counts triple and breadth across years counts double.
  context   the word only ever appeared inside a question's stem. It earns its
            place because a candidate plausibly cannot read the question without
            it (ADR-0011), but it was never itself examined.

A tested word outranks a context word, because a word the exam actually tested
is the thing a candidate is studying for. Within each kind: tested words by
`stats.priority`, context words by the judges' importance x difficulty. A word
that is both sorts as tested and keeps its context data.

Emits extraction/state/generation-queue.json and .md. Reads the lexicon; writes
nothing to content/.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
STATE = ROOT / "extraction" / "state"
LEX = ROOT / "content" / "lexicon"


def main() -> int:
    sel = json.loads((STATE / "stem-vocab-selection.json").read_text(encoding="utf-8"))
    judged = {w["id"]: w for w in sel["words"]}

    rows = []
    for path in sorted(LEX.glob("*.json")):
        d = json.loads(path.read_text(encoding="utf-8"))
        st = d["stats"]
        tested = st["timesTested"] > 0
        ctx = judged.get(d["id"])
        rows.append({
            "id": d["id"],
            "lemma": d["lemma"],
            "kind": "both" if tested and ctx else "tested" if tested else "context",
            "priority": st["priority"],
            "timesTested": st["timesTested"],
            "timesAsAnswer": st["timesAsAnswer"],
            "timesAsContext": st.get("timesAsContext", 0),
            "years": sorted(st["byYear"], reverse=True),
            "tier": ctx["tier"] if ctx else None,
            "importance": ctx["importance"] if ctx else None,
            "difficulty": ctx["difficulty"] if ctx else None,
            "gloss": ctx["gloss"] if ctx else None,
            "domainFieldCodes": (d.get("domain") or {}).get("fieldCodes"),
            "hasTranslation": bool(d["translations"]),
        })

    rows.sort(key=lambda r: (
        0 if r["kind"] in ("tested", "both") else 1,
        -r["priority"],
        -(r["importance"] or 0) * (r["difficulty"] or 0),
        -r["timesAsContext"],
        r["id"],
    ))
    for i, r in enumerate(rows, 1):
        r["rank"] = i

    done = sum(1 for r in rows if r["hasTranslation"])
    out = {
        "total": len(rows),
        "withTranslation": done,
        "remaining": len(rows) - done,
        "byKind": {
            k: sum(1 for r in rows if r["kind"] == k) for k in ("tested", "both", "context")
        },
        "order": "tested words by stats.priority, then context words by importance x difficulty",
        "words": rows,
    }
    (STATE / "generation-queue.json").write_text(
        json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")

    lines = [
        "# Generation queue",
        "",
        "%d words, %d still without a translation. Generated by "
        "`extraction/scripts/s9_generation_queue.py` - do not edit by hand."
        % (len(rows), len(rows) - done),
        "",
        "| # | word | kind | prio | tested | answer | ctx | years |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append("| %d | `%s` | %s | %d | %d | %d | %d | %s |" % (
            r["rank"], r["id"], r["kind"], r["priority"], r["timesTested"],
            r["timesAsAnswer"], r["timesAsContext"], ",".join(r["years"])))
    (STATE / "generation-queue.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("queue: %d words   tested %d   both %d   context %d"
          % (len(rows), out["byKind"]["tested"], out["byKind"]["both"], out["byKind"]["context"]))
    print("with a translation already: %d   remaining: %d" % (done, len(rows) - done))
    print("\nfirst 10:")
    for r in rows[:10]:
        print("  %3d  %-16s %-8s prio %-3d tested %dx answer %dx"
              % (r["rank"], r["id"], r["kind"], r["priority"], r["timesTested"], r["timesAsAnswer"]))
    print("\nfirst 5 context words:")
    for r in [x for x in rows if x["kind"] == "context"][:5]:
        print("  %3d  %-16s tier %d  imp %d dif %d  %s"
              % (r["rank"], r["id"], r["tier"], r["importance"], r["difficulty"], r["gloss"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
